// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axphybusgdnjbffblbuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cGh5YnVzZ2RuamJmZmJsYnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTM2NjgsImV4cCI6MjA2NTkyOTY2OH0.z68A53RYo8lA_UeMFcwxz2_04VOtLgazZLAlyOpbGNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);